---

- hosts: all
  remote_user: centos
  become: true
  
  roles:
    - locale 
    - timezone
    - openjdk

  tasks:

    - name: FRONT | Install nodejs lts | Script fetch 
      get_url: 
        url:  https://rpm.nodesource.com/setup_4.x
        dest: /tmp/nodesetup.sh
        mode: 777

    - stat: path=/etc/yum.repos.d/nodesource.repo
      register: tmp
 
    - name: FRONT | Install nodejs lts | Repo instalation
      shell: /tmp/nodesetup.sh
      when: tmp.stat.islnk is not defined

    - name: FRONT | Install nodejs lts | yum insalation 
      yum: name=nodejs state=latest

    - name: FRONT | Create node user
      user: name=node comment="node user" 

